name: Audit

on:
  push:
    branches: [main, robadams-fix-ci]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5

    - name: Verify dependencies
      run: go verify ./...

    - name: Run gofmt
      run:  test -z $$(gofmt -l .)

    - name: Build
      run: go build ./...

    - name: Run go vet
      run: go vet ./...

    - name: Detect ineffectual assignments
      run:  go run github.com/gordonklaus/ineffassign@latest ./...

    - name: Run staticcheck
      run:  go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...

    - name: Run vulncheck
      run:  go run golang.org/x/vuln/cmd/govulncheck@latest ./...

    - name: Run golint
      run:  go run github.com/mgechev/revive@latest -set_exit_status ./...

    - name: Run tests
      run:  go test -race -buildvcs -vet=off ./...
